// Code generated by protoc-gen-equal-go. DO NOT EDIT.
// source: internal/testprotos/test/weak1/test_weak.proto

package weak1

func (x *WeakImportMessage1) Equal(y *WeakImportMessage1) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if x == y {
		return true
	}
	return x.A == y.A
}
