// Code generated by protoc-gen-equal-go. DO NOT EDIT.
// source: internal/testprotos/test/weak1/test_weak.proto

package weak1

func (x *WeakImportMessage1) Equal(y *WeakImportMessage1) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if p, q := x.A, y.A; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return true
}
